server:
  port: 8081
  servlet:
    context-path: /KeepMovingFiness

# 引入mybatis的两个配置文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://121.199.58.63:3306/keepmoving?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: km
    password: Root123!
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#    拦截器配置
#    static-path-pattern: /static/**

#      配置redis
  redis:
    host: localhost
    port: 6379
    database: 10
    password: success

  data:
    mongodb:
      database: km_comment
      host: 121.199.58.63
      port: 27017
