package com.keepmoving.fitness.entity.personInfo;

import java.io.Serializable;

public class ThirdPart implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_part.id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_part.user_id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_part.login_method
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private String loginMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_part.unique_id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table third_part
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_part.id
     *
     * @return the value of third_part.id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_part.id
     *
     * @param id the value for third_part.id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_part.user_id
     *
     * @return the value of third_part.user_id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_part.user_id
     *
     * @param userId the value for third_part.user_id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_part.login_method
     *
     * @return the value of third_part.login_method
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public String getLoginMethod() {
        return loginMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_part.login_method
     *
     * @param loginMethod the value for third_part.login_method
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public void setLoginMethod(String loginMethod) {
        this.loginMethod = loginMethod == null ? null : loginMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_part.unique_id
     *
     * @return the value of third_part.unique_id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_part.unique_id
     *
     * @param uniqueId the value for third_part.unique_id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId == null ? null : uniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_part
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", loginMethod=").append(loginMethod);
        sb.append(", uniqueId=").append(uniqueId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}