package com.keepmoving.fitness.entity.personInfo;


import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.Date;

@Component
public class UserBaseInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.user_no
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.username
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.gender
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.birthday
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.city
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.height
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Float height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.weight
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base_info.signature
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base_info
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    public UserBaseInfo() {
    }

    public UserBaseInfo(Integer id, Long userId, String username, String gender, Date birthday, String city, Float height, Float weight, String signature) {
        this.id = id;
        this.userId = userId;
        this.username = username;
        this.gender = gender;
        this.birthday = birthday;
        this.city = city;
        this.height = height;
        this.weight = weight;
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base_info.id
     *
     * @return the value of user_base_info.id
     *
     * @mbggenerated Fri Sep 27 23:42:29 CST 2019
     */

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Float getHeight() {
        return height;
    }

    public void setHeight(Float height) {
        this.height = height;
    }

    public Float getWeight() {
        return weight;
    }

    public void setWeight(Float weight) {
        this.weight = weight;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("UserBaseInfo{");
        sb.append("id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", username='").append(username).append('\'');
        sb.append(", gender='").append(gender).append('\'');
        sb.append(", birthday=").append(birthday);
        sb.append(", city='").append(city).append('\'');
        sb.append(", height=").append(height);
        sb.append(", weight=").append(weight);
        sb.append(", signature='").append(signature).append('\'');
        sb.append('}');
        return sb.toString();
    }
}